services:
    softleister_starrating.listener.insert_tags:
        class: Softleister\ContaoStarRatingBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"
        public: true
